version: "3.8"

services: 
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
       PORT: 3000
    ports:
      - "3000:3000"

  postgres: 
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: ecommerce
